import { BoardConfig, Coord, toPoint } from "./types";

export const LEVELS: Record<string, BoardConfig> = {
  easy: {
    rows: 9,
    cols: 9,
    start: toPoint([2, 8]),
    end: toPoint([7, 0]),
    rocks: ([
      [1, 3],
      [1, 4],
      [3, 7],
      [4, 1],
      [4, 2],
      [4, 6],
      [5, 4],
      [5, 7],
      [6, 1],
    ] as Coord[]).map(toPoint),
    // Only for display; logic uses rows/cols/rocks/start/end.
    grid: [
      'WWWWWWWEW',
      'W   R R W',
      'W   R   W',
      'WR      W',
      'WR   R  W',
      'W       W',
      'W   R   W',
      'W  R R  W',
      'WWSWWWWWW',
    ],
  },

  medium: {
    rows: 14,
    cols: 14,
    start: toPoint([1, 13]),
    end: toPoint([10, 0]),
    rocks: ([
      [1, 1],
      [2, 10],
      [3, 8],
      [3, 11],
      [4, 2],
      [4, 9],
      [5, 7],
      [5, 11],
      [6, 1],
      [7, 3],
      [7, 4],
      [8, 12],
      [9, 3],
      [9, 8],
      [12, 1],
      [12, 7],
    ] as Coord[]).map(toPoint),
    grid: [
      'WWWWWWWWWWEWWW',
      'WR    R     RW',
      'W   R        W',
      'W      R R   W',
      'W      R     W',
      'W            W',
      'W            W',
      'W    R      RW',
      'W  R     R   W',
      'W   R        W',
      'W R          W',
      'W  R R       W',
      'W       R    W',
      'WSWWWWWWWWWWWW',
    ],
  },

  hard: {
    rows: 19,
    cols: 19,
    start: toPoint([1, 18]),
    end: toPoint([18, 5]),
    rocks: ([
      [1, 2],
      [1, 11],
      [2, 1],
      [3, 8],
      [4, 7],
      [4, 14],
      [5, 6],
      [5, 16],
      [6, 13],
      [6, 14],
      [6, 17],
      [7, 4],
      [7, 7],
      [8, 6],
      [8, 12],
      [8, 17],
      [9, 14],
      [9, 17],
      [10, 9],
      [10, 12],
      [11, 12],
      [11, 17],
      [14, 1],
      [14, 4],
      [14, 6],
      [14, 11],
      [14, 13],
      [15, 3],
      [15, 5],
      [15, 7],
      [15, 11],
      [15, 16],
      [15, 17],
      [16, 7],
      [16, 14],
      [17, 4],
      [17, 7],
      [17, 13],
    ] as Coord[]).map(toPoint),
    grid: [
      'WWWWWWWWWWWWWWWWWWW',
      'W R           R   W',
      'WR                W',
      'W              R  W',
      'W      R      R  RW',
      'W              R  E',
      'W    R  R     R   W',
      'W   R  R       RRRW',
      'W  R              W',
      'W         R       W',
      'W                 W',
      'WR            RR  W',
      'W       R RR      W',
      'W     R       R  RW',
      'W   R R  R      R W',
      'W                 W',
      'W    R         R  W',
      'W     R RR R   R  W',
      'WSWWWWWWWWWWWWWWWWW',
    ],
  },

  extreme: {
    rows: 22,
    cols: 22,
    start: toPoint([0, 4]),
    end: toPoint([0, 11]),
    rocks: ([
      [1, 3],
      [1, 14],
      [2, 4],
      [2, 17],
      [2, 20],
      [3, 8],
      [3, 18],
      [4, 5],
      [4, 14],
      [4, 15],
      [4, 18],
      [5, 12],
      [5, 13],
      [5, 15],
      [6, 15],
      [7, 6],
      [7, 9],
      [7, 14],
      [8, 14],
      [8, 17],
      [8, 18],
      [8, 20],
      [9, 10],
      [9, 15],
      [9, 18],
      [11, 1],
      [11, 2],
      [11, 19],
      [11, 20],
      [12, 6],
      [12, 11],
      [13, 11],
      [13, 19],
      [14, 6],
      [15, 4],
      [15, 8],
      [15, 13],
      [15, 15],
      [15, 18],
      [15, 19],
      [16, 9],
      [16, 10],
      [16, 18],
      [18, 6],
      [18, 10],
      [18, 14],
      [18, 16],
      [19, 7],
      [19, 12],
      [19, 16],
      [20, 14],
      [20, 16],
    ] as Coord[]).map(toPoint),
    grid: [
      'WWWWWWWWWWWWWWWWWWWWWW',
      'W          R         W',
      'W          R         W',
      'WR                   W',
      'S R            R     W',
      'W   R                W',
      'W      R    R R   R  W',
      'W                  R W',
      'W  R           R     W',
      'W      R        R    W',
      'W        R      R R  W',
      'E           RR       W',
      'W    R             R W',
      'W    R         R     W',
      'WR  R  RR         R RW',
      'W   RRR  R     R     W',
      'W                 RRRW',
      'W R     R            W',
      'W  RR   RR     RR    W',
      'W          R R R     W',
      'W R     R  R         W',
      'WWWWWWWWWWWWWWWWWWWWWW',
    ],
  },
};
